
services:
  postgres:
    image: postgres:16
    container_name: meu_postgres
    restart: always
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: nome_do_banco
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
